### ISSUE TITLE
List of Ideas

### ISSUE THREAD

**Issue by MikaAldreya** [tbdscripts/cosmo-issues#65] opened 2021-12-25 15:11 UTC
### 💡 Description of the feature

To be able to delete an order so that the person can buy it back if it is not possible to buy multiple orders.

Be able to create fake purchases to add money to the global pool to integrate for example external purchases to the sites.

Added a payment method called credit that would allow each person to buy credits through the payment methods activated, this would firstly allow the possibility of giving credits through the management menu.

Through this mode of credit, it would be possible to integrate a paysafecard system, basically the player enters his paysafecard and it is on hold until someone validates it on the management menu.

Last but not least, a working in-game notification system would be nice!

Translated with www.DeepL.com/Translator (free version)

### ❗ Examples of the feature

idk like prometheus

**Comment by mexdeloo** [comment] 2021-12-31 18:59
Duplicate of #29

**Closed as completed by mexdeloo** 2021-12-31 18:59 UTC
Labels: duplicate, enhancement, platform: web
