### ISSUE TITLE
Rank Sync 

### ISSUE THREAD

**Issue by Andrew-fuse** [tbdscripts/cosmo-issues#58] opened 2021-11-16 20:04 UTC
### Description of the feature

Basic feature where Cosmo has an in-game integration with ULX/ SAM or a admin mod and you can sync Certain Ranks Such as Bans so people with Banned Cosmo role can only do certain things and to prevent Abuse of forums

### Examples of the feature

Somewhat like Babl had integration

### Alternatives for the feature

N/A

### Additional Context

N/a

**Comment by LucaTanks** [comment] 2022-05-31 21:22
Duplicate of #43

**Closed as completed** 2022-05-31 21:22 UTC
